apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: amq-master-svc
  name: amq-master-svc
spec:
  ports:
  - name: 1883-tcp
    port: 1883
    protocol: TCP
    targetPort: 1883
  - name: 5445-tcp
    port: 5445
    protocol: TCP
    targetPort: 5445
  - name: 5672-tcp
    port: 5672
    protocol: TCP
    targetPort: 5672
  - name: 8161-tcp
    port: 8161
    protocol: TCP
    targetPort: 8161
  - name: 9404-tcp
    port: 9404
    protocol: TCP
    targetPort: 9404
  - name: 61613-tcp
    port: 61613
    protocol: TCP
    targetPort: 61613
  - name: 61616-tcp
    port: 61616
    protocol: TCP
    targetPort: 61616
  selector:
    app: amq-master-svc
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
